### ISSUE TITLE
I want to collaborate

### ISSUE THREAD

**Issue by SirNoob97** [CalebYPI/RedBusTours#28]
Hello, I found this project on [good first issues](https://goodfirstissues.com/), but i have some doubts 
- what's the point of the project? 
- where can i get some info? 
- do you have a community or something like that?

**Comment by CalebYPI** [comment]
Hi SirNood97, thank you for your interest in wanting to collaborate, however, this repository is a university assignment and is closed to everyone except my colleagues.
